# site properties and page defaults
title: Ultrafast Quantum Probe Lab
share_title: Ultrafast Quantum Probe Lab (UQP), Zhejiang University
subtitle: Zhejiang University
description: "The Ultrafast Quantum Probe Lab at Zhejiang University undertakes research in surface and low dimensional quantum material systems, with focus on advanced scanning probe techniques to reach unprecedented spatial, temporal, and momentum resolutions."
keywords: [uqp, scanning probe, scanning tunneling microscope, quantum twisting microscope, ultrafast lasers, THz, 2D materials, moir√© supercell, quantum sensing, quantum coherence, zhejiang university]
author: "Ultrafast Quantum Probe Lab"
footer: images/background_imp-light.jpg
proofer: false
header-dark: false


url:  https://www.uqplab.com
baseurl: ''
# Sitemap settings
sitemap:
  filename: sitemap.xml
  exclude:
    - "/404.html"
    - "/.bundle/"
    - "/_cite/"

# site social media and other links
links:
  email: likunw@zju.edu.cn
  # orcid: 0000-0001-8713-9213
  google-scholar: 
  github: wanglikun08
  # twitter: YourLabHandle
  # youtube: YourLabChannel

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-loading-lazy
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-minifier

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

sass:
  style: compressed  # This compresses the output CSS

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts
  - _redirects

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

jekyll-minifier:
  exclude: ['*.xml', '*.json', '*.txt']  # Files to exclude from minification
  remove_spaces_inside_tags: true        # Default: true
  remove_multi_spaces: true              # Default: true
  remove_comments: true                  # Default: true
  preserve_php: true                     # Default: false
  remove_intertag_spaces: true           # Default: false
  compress_css: false                    # Default: true
  compress_javascript: false             # Default: true
  compress_json: false                   # Default: true
